// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwqzewsoortetapeadai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3cXpld3Nvb3J0ZXRhcGVhZGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NTMxNDcsImV4cCI6MjA5MTMyOTE0N30.uEKBdv4tRKTVHkUUFAIZQ39lMj9pDR3XYHnTuSIk6Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});