// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiiazbdqpbnpfxwibyjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpaWF6YmRxcGJucGZ4d2lieWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODczMTAsImV4cCI6MjA3MjU2MzMxMH0.LSwSmMEVWwx7_yGeMtzxpejb_xAysFQLI7weg6tcQPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});